CREATE OR ALTER PROCEDURE dbo.PAQ_PartesProduccion_TiposTareaGet
    @IdTipoTarea INT
AS
BEGIN
    SET NOCOUNT ON;

    IF OBJECT_ID(N'dbo.PQ_PRD_TIPOS_TAREA', N'U') IS NULL
    BEGIN
        SELECT CAST(NULL AS INT) AS id WHERE 1 = 0;
        RETURN;
    END

    SELECT TOP 1
        CAST(ID_TIPO_TAREA AS INT) AS id,
        LTRIM(RTRIM(CAST(CODIGO_TIPO_TAREA AS NVARCHAR(20)))) AS codigo,
        LTRIM(RTRIM(CAST(NOMBRE AS NVARCHAR(100)))) AS nombre,
        CAST(ISNULL(ACTIVO, 0) AS BIT) AS activo
    FROM dbo.PQ_PRD_TIPOS_TAREA
    WHERE ID_TIPO_TAREA = @IdTipoTarea;
END
GO
