CREATE OR ALTER PROCEDURE dbo.PAQ_OrdenesCompra_Get
    @talon_oc   INT,
    @n_orden_co NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @nro NVARCHAR(50) = LTRIM(RTRIM(ISNULL(@n_orden_co, N'')));

    IF OBJECT_ID(N'dbo.CPA35', N'U') IS NULL
    BEGIN
        SELECT CAST(NULL AS INT) AS idCpa35 WHERE 1 = 0;
        SELECT CAST(NULL AS INT) AS idCpa36 WHERE 1 = 0;
        SELECT CAST(NULL AS INT) AS nPlaneOc WHERE 1 = 0;
        SELECT CAST(NULL AS INT) AS nRenglonOc WHERE 1 = 0;
        RETURN;
    END

    DECLARE @hasIdCpa35 BIT = CASE WHEN COL_LENGTH(N'dbo.CPA35', N'ID_CPA35') IS NOT NULL THEN 1 ELSE 0 END;
    DECLARE @hasRowVersion BIT = CASE WHEN COL_LENGTH(N'dbo.CPA35', N'ROW_VERSION') IS NOT NULL THEN 1 ELSE 0 END;
    DECLARE @hasObs BIT = CASE WHEN COL_LENGTH(N'dbo.CPA35', N'OBSERVACIONES') IS NOT NULL THEN 1 ELSE 0 END;
    DECLARE @hasObsCorta BIT = CASE WHEN COL_LENGTH(N'dbo.CPA35', N'OBSERVACIO') IS NOT NULL THEN 1 ELSE 0 END;

    -- RS0 cabecera
    DECLARE @sqlCab NVARCHAR(MAX) = N'
        SELECT TOP 1
            ' + CASE WHEN @hasIdCpa35 = 1 THEN N'CAST(c.ID_CPA35 AS INT)' ELSE N'CAST(NULL AS INT)' END + N' AS idCpa35,
            CAST(c.TALONARIO AS INT) AS talonOc,
            LTRIM(RTRIM(CAST(c.N_ORDEN_CO AS NVARCHAR(50)))) AS nOrdenCo,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'ESTADO') IS NOT NULL THEN N'CAST(c.ESTADO AS INT)' ELSE N'CAST(NULL AS INT)' END + N' AS estado,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'TOTAL_CTE') IS NOT NULL THEN N'CAST(c.TOTAL_CTE AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS totalCte,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'TOTAL_EXT') IS NOT NULL THEN N'CAST(c.TOTAL_EXT AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS totalExt,
            ' + CASE WHEN @hasRowVersion = 1 THEN N'CAST(c.ROW_VERSION AS VARBINARY(8))' ELSE N'CAST(NULL AS VARBINARY(8))' END + N' AS rowVersion,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'COD_PROVEE') IS NOT NULL THEN N'LTRIM(RTRIM(CAST(c.COD_PROVEE AS NVARCHAR(20))))' ELSE N'CAST(NULL AS NVARCHAR(20))' END + N' AS codProvee,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'FEC_EMISIO') IS NOT NULL THEN N'CONVERT(VARCHAR(10), c.FEC_EMISIO, 23)' ELSE N'CAST(NULL AS VARCHAR(10))' END + N' AS fechaEmisio,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'FEC_VIGENC') IS NOT NULL THEN N'CONVERT(VARCHAR(10), c.FEC_VIGENC, 23)' ELSE N'CAST(NULL AS VARCHAR(10))' END + N' AS fechaVigenc,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'FEC_GENER') IS NOT NULL THEN N'CONVERT(VARCHAR(10), c.FEC_GENER, 23)' ELSE N'CAST(NULL AS VARCHAR(10))' END + N' AS fechaGener,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'MON_CTE') IS NOT NULL THEN N'CAST(c.MON_CTE AS BIT)' ELSE N'CAST(1 AS BIT)' END + N' AS monCte,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'COTIZ') IS NOT NULL THEN N'CAST(c.COTIZ AS FLOAT)' ELSE N'CAST(1 AS FLOAT)' END + N' AS cotiz,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'COD_LISTA') IS NOT NULL THEN N'CAST(c.COD_LISTA AS INT)' ELSE N'CAST(0 AS INT)' END + N' AS codLista,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'COND_COMPR') IS NOT NULL THEN N'CAST(c.COND_COMPR AS INT)' ELSE N'CAST(0 AS INT)' END + N' AS condCompr,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'COD_COMPRA') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(c.COD_COMPRA AS NVARCHAR(20)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(20))' END + N' AS codCompra,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'NRO_SUCURS') IS NOT NULL THEN N'CAST(c.NRO_SUCURS AS INT)' ELSE N'CAST(0 AS INT)' END + N' AS nroSucurs,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'PORC_BONIF') IS NOT NULL THEN N'CAST(c.PORC_BONIF AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS porcBonif,
            ' + CASE WHEN @hasObs = 1 THEN N'LTRIM(RTRIM(CAST(c.OBSERVACIONES AS NVARCHAR(MAX))))'
                     WHEN @hasObsCorta = 1 THEN N'LTRIM(RTRIM(CAST(c.OBSERVACIO AS NVARCHAR(MAX))))'
                     ELSE N'CAST(N'''' AS NVARCHAR(MAX))' END + N' AS observaciones,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'LEYENDA_1') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(c.LEYENDA_1 AS NVARCHAR(200)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(200))' END + N' AS leyenda1,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'LEYENDA_2') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(c.LEYENDA_2 AS NVARCHAR(200)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(200))' END + N' AS leyenda2,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'LEYENDA_3') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(c.LEYENDA_3 AS NVARCHAR(200)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(200))' END + N' AS leyenda3,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'LEYENDA_4') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(c.LEYENDA_4 AS NVARCHAR(200)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(200))' END + N' AS leyenda4,
            ' + CASE WHEN COL_LENGTH(N'dbo.CPA35', N'LEYENDA_5') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(c.LEYENDA_5 AS NVARCHAR(200)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(200))' END + N' AS leyenda5
        FROM dbo.CPA35 c
        WHERE c.TALONARIO = @p_talon
          AND LTRIM(RTRIM(CAST(c.N_ORDEN_CO AS NVARCHAR(50)))) = @p_nro';

    EXEC sp_executesql @sqlCab,
        N'@p_talon INT, @p_nro NVARCHAR(50)',
        @p_talon = @talon_oc, @p_nro = @nro;

    DECLARE @idCpa35 INT = NULL;
    IF @hasIdCpa35 = 1
    BEGIN
        SELECT TOP 1 @idCpa35 = CAST(ID_CPA35 AS INT)
        FROM dbo.CPA35
        WHERE TALONARIO = @talon_oc
          AND LTRIM(RTRIM(CAST(N_ORDEN_CO AS NVARCHAR(50)))) = @nro;
    END

    -- RS1 renglones
    IF OBJECT_ID(N'dbo.CPA36', N'U') IS NULL
    BEGIN
        SELECT CAST(NULL AS INT) AS idCpa36 WHERE 1 = 0;
    END
    ELSE
    BEGIN
        DECLARE @sqlRen NVARCHAR(MAX) = N'
            SELECT
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'ID_CPA36') IS NOT NULL THEN N'CAST(r.ID_CPA36 AS INT)' ELSE N'CAST(NULL AS INT)' END + N' AS idCpa36,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'N_RENGL_OC') IS NOT NULL THEN N'CAST(r.N_RENGL_OC AS INT)' ELSE N'CAST(0 AS INT)' END + N' AS nRenglonOc,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'COD_ARTICU') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(r.COD_ARTICU AS NVARCHAR(50)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(50))' END + N' AS codArticu,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'COD_DEPOSI') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(r.COD_DEPOSI AS NVARCHAR(20)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(20))' END + N' AS codDeposi,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'CAN_PEDIDA') IS NOT NULL THEN N'CAST(r.CAN_PEDIDA AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS cantPedida,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'CAN_PENDIE') IS NOT NULL THEN N'CAST(r.CAN_PENDIE AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS cantPendie,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'CAN_RECIBI') IS NOT NULL THEN N'CAST(r.CAN_RECIBI AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS cantRecibi,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'CAN_PEDIDA_2') IS NOT NULL THEN N'CAST(r.CAN_PEDIDA_2 AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS cantPedida2,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'PRECIO') IS NOT NULL THEN N'CAST(r.PRECIO AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS precio,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'PORC_DCTO') IS NOT NULL THEN N'CAST(r.PORC_DCTO AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS porcDcto,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'ESTADO') IS NOT NULL THEN N'CAST(r.ESTADO AS INT)' ELSE N'CAST(0 AS INT)' END + N' AS estado,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'UNIDAD_MEDIDA_SELECCIONADA') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(r.UNIDAD_MEDIDA_SELECCIONADA AS NVARCHAR(20)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(20))' END + N' AS unidadMedidaSeleccionada,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'COD_CPA51') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(r.COD_CPA51 AS NVARCHAR(20)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(20))' END + N' AS codSector,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'COD_CPA131') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(r.COD_CPA131 AS NVARCHAR(20)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(20))' END + N' AS codSolic,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'OBSERVACIONES') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(r.OBSERVACIONES AS NVARCHAR(MAX)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(MAX))' END + N' AS observaciones,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'PENDIENTE_FACTURAR') IS NOT NULL THEN N'CAST(r.PENDIENTE_FACTURAR AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS pendienteFacturar,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'CANTIDAD_FACTURADA') IS NOT NULL THEN N'CAST(r.CANTIDAD_FACTURADA AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS cantidadFacturada,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'DESCRIPCION_ARTICULO') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(r.DESCRIPCION_ARTICULO AS NVARCHAR(200)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(200))' END + N' AS descripcionCpa36,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA36', N'DESC_ADICIONAL_ARTICULO') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(r.DESC_ADICIONAL_ARTICULO AS NVARCHAR(200)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(200))' END + N' AS descAdicionalCpa36
            FROM dbo.CPA36 r
            WHERE ';

        IF COL_LENGTH(N'dbo.CPA36', N'ID_CPA35') IS NOT NULL AND @idCpa35 IS NOT NULL
            SET @sqlRen = @sqlRen + N'r.ID_CPA35 = @p_id';
        ELSE
            SET @sqlRen = @sqlRen + N'r.TALONARIO = @p_talon AND LTRIM(RTRIM(CAST(r.N_ORDEN_CO AS NVARCHAR(50)))) = @p_nro';

        IF COL_LENGTH(N'dbo.CPA36', N'N_RENGL_OC') IS NOT NULL
            SET @sqlRen = @sqlRen + N' ORDER BY r.N_RENGL_OC';

        EXEC sp_executesql @sqlRen,
            N'@p_id INT, @p_talon INT, @p_nro NVARCHAR(50)',
            @p_id = @idCpa35, @p_talon = @talon_oc, @p_nro = @nro;
    END

    -- RS2 planes
    IF OBJECT_ID(N'dbo.CPA37', N'U') IS NULL
    BEGIN
        SELECT CAST(NULL AS INT) AS nPlaneOc WHERE 1 = 0;
    END
    ELSE
    BEGIN
        DECLARE @sqlPlan NVARCHAR(MAX);

        IF COL_LENGTH(N'dbo.CPA37', N'ID_CPA35') IS NOT NULL AND @idCpa35 IS NOT NULL
        BEGIN
            SET @sqlPlan = N'
                SELECT
                    ' + CASE WHEN COL_LENGTH(N'dbo.CPA37', N'ID_CPA36') IS NOT NULL THEN N'CAST(p.ID_CPA36 AS INT)' ELSE N'CAST(NULL AS INT)' END + N' AS idCpa36,
                    ' + CASE WHEN COL_LENGTH(N'dbo.CPA37', N'N_RENGL_OC') IS NOT NULL THEN N'CAST(p.N_RENGL_OC AS INT)' ELSE N'CAST(0 AS INT)' END + N' AS nRenglonOc,
                    ' + CASE WHEN COL_LENGTH(N'dbo.CPA37', N'N_PLANE_OC') IS NOT NULL THEN N'CAST(p.N_PLANE_OC AS INT)' ELSE N'CAST(NULL AS INT)' END + N' AS nPlaneOc,
                    ' + CASE WHEN COL_LENGTH(N'dbo.CPA37', N'FEC_RECEPC') IS NOT NULL THEN N'CONVERT(VARCHAR(10), p.FEC_RECEPC, 23)' ELSE N'CAST(NULL AS VARCHAR(10))' END + N' AS fechaRecepc,
                    ' + CASE WHEN COL_LENGTH(N'dbo.CPA37', N'CANTIDAD') IS NOT NULL THEN N'CAST(p.CANTIDAD AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS cantidad,
                    ' + CASE WHEN COL_LENGTH(N'dbo.CPA37', N'CANTIDAD_2') IS NOT NULL THEN N'CAST(p.CANTIDAD_2 AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS cantidad2
                FROM dbo.CPA37 p
                WHERE p.ID_CPA35 = @p_id';
        END
        ELSE IF COL_LENGTH(N'dbo.CPA37', N'TALONARIO') IS NOT NULL
        BEGIN
            SET @sqlPlan = N'
                SELECT
                    ' + CASE WHEN COL_LENGTH(N'dbo.CPA37', N'ID_CPA36') IS NOT NULL THEN N'CAST(p.ID_CPA36 AS INT)' ELSE N'CAST(NULL AS INT)' END + N' AS idCpa36,
                    ' + CASE WHEN COL_LENGTH(N'dbo.CPA37', N'N_RENGL_OC') IS NOT NULL THEN N'CAST(p.N_RENGL_OC AS INT)' ELSE N'CAST(0 AS INT)' END + N' AS nRenglonOc,
                    ' + CASE WHEN COL_LENGTH(N'dbo.CPA37', N'N_PLANE_OC') IS NOT NULL THEN N'CAST(p.N_PLANE_OC AS INT)' ELSE N'CAST(NULL AS INT)' END + N' AS nPlaneOc,
                    ' + CASE WHEN COL_LENGTH(N'dbo.CPA37', N'FEC_RECEPC') IS NOT NULL THEN N'CONVERT(VARCHAR(10), p.FEC_RECEPC, 23)' ELSE N'CAST(NULL AS VARCHAR(10))' END + N' AS fechaRecepc,
                    ' + CASE WHEN COL_LENGTH(N'dbo.CPA37', N'CANTIDAD') IS NOT NULL THEN N'CAST(p.CANTIDAD AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS cantidad,
                    ' + CASE WHEN COL_LENGTH(N'dbo.CPA37', N'CANTIDAD_2') IS NOT NULL THEN N'CAST(p.CANTIDAD_2 AS FLOAT)' ELSE N'CAST(0 AS FLOAT)' END + N' AS cantidad2
                FROM dbo.CPA37 p
                WHERE p.TALONARIO = @p_talon
                  AND LTRIM(RTRIM(CAST(p.N_ORDEN_CO AS NVARCHAR(50)))) = @p_nro';
        END
        ELSE
        BEGIN
            SET @sqlPlan = N'SELECT CAST(NULL AS INT) AS nPlaneOc WHERE 1 = 0';
        END

        IF COL_LENGTH(N'dbo.CPA37', N'N_PLANE_OC') IS NOT NULL AND CHARINDEX(N'WHERE 1 = 0', @sqlPlan) = 0
            SET @sqlPlan = @sqlPlan + N' ORDER BY p.N_RENGL_OC, p.N_PLANE_OC';

        EXEC sp_executesql @sqlPlan,
            N'@p_id INT, @p_talon INT, @p_nro NVARCHAR(50)',
            @p_id = @idCpa35, @p_talon = @talon_oc, @p_nro = @nro;
    END

    -- RS3 textos CPA41
    IF OBJECT_ID(N'dbo.CPA41', N'U') IS NULL
       OR COL_LENGTH(N'dbo.CPA41', N'N_RENGL_OC') IS NULL
       OR COL_LENGTH(N'dbo.CPA41', N'TALONARIO') IS NULL
    BEGIN
        SELECT CAST(NULL AS INT) AS nRenglonOc WHERE 1 = 0;
    END
    ELSE
    BEGIN
        DECLARE @sqlTxt NVARCHAR(MAX) = N'
            SELECT
                CAST(t.N_RENGL_OC AS INT) AS nRenglonOc,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA41', N'DESCRIP') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(t.DESCRIP AS NVARCHAR(200)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(200))' END + N' AS descripcion,
                ' + CASE WHEN COL_LENGTH(N'dbo.CPA41', N'DESC_ADICI') IS NOT NULL THEN N'NULLIF(LTRIM(RTRIM(CAST(t.DESC_ADICI AS NVARCHAR(200)))), N'''')' ELSE N'CAST(NULL AS NVARCHAR(200))' END + N' AS descAdicional
            FROM dbo.CPA41 t
            WHERE t.TALONARIO = @p_talon
              AND LTRIM(RTRIM(CAST(t.N_ORDEN_CO AS NVARCHAR(50)))) = @p_nro';

        EXEC sp_executesql @sqlTxt,
            N'@p_talon INT, @p_nro NVARCHAR(50)',
            @p_talon = @talon_oc, @p_nro = @nro;
    END
END
GO
