CREATE OR ALTER PROCEDURE dbo.PAQ_PartesProduccion_ConceptosTiempoGet
    @IdConceptoTiempo INT
AS
BEGIN
    SET NOCOUNT ON;

    IF OBJECT_ID(N'dbo.PQ_PRD_CONCEPTOS_TIEMPO', N'U') IS NULL
    BEGIN
        SELECT CAST(NULL AS INT) AS id WHERE 1 = 0;
        RETURN;
    END

    IF COL_LENGTH(N'dbo.PQ_PRD_CONCEPTOS_TIEMPO', N'HABITUAL') IS NULL
       OR COL_LENGTH(N'dbo.PQ_PRD_CONCEPTOS_TIEMPO', N'ID_TIPO_TAREA') IS NULL
    BEGIN
        SELECT CAST(NULL AS INT) AS id WHERE 1 = 0;
        RETURN;
    END

    SELECT TOP 1
        CAST(c.ID_CONCEPTO_TIEMPO AS INT) AS id,
        LTRIM(RTRIM(CAST(c.CODIGO_CONCEPTO AS NVARCHAR(20)))) AS codigo,
        LTRIM(RTRIM(CAST(c.NOMBRE AS NVARCHAR(120)))) AS nombre,
        CAST(ISNULL(c.ES_PRODUCTIVO, 0) AS BIT) AS es_productivo,
        CAST(ISNULL(c.ACTIVO, 0) AS BIT) AS activo,
        CAST(ISNULL(c.HABITUAL, 0) AS BIT) AS habitual,
        CAST(c.ID_TIPO_TAREA AS INT) AS id_tipo_tarea,
        CASE
            WHEN tt.ID_TIPO_TAREA IS NULL THEN CAST(NULL AS NVARCHAR(20))
            ELSE LTRIM(RTRIM(CAST(tt.CODIGO_TIPO_TAREA AS NVARCHAR(20))))
        END AS tipo_tarea_codigo,
        CASE
            WHEN tt.ID_TIPO_TAREA IS NULL THEN CAST(NULL AS NVARCHAR(100))
            ELSE LTRIM(RTRIM(CAST(tt.NOMBRE AS NVARCHAR(100))))
        END AS tipo_tarea_nombre,
        CASE
            WHEN tt.ID_TIPO_TAREA IS NULL THEN CAST(NULL AS NVARCHAR(150))
            WHEN LTRIM(RTRIM(CAST(ISNULL(tt.CODIGO_TIPO_TAREA, N'') AS NVARCHAR(20)))) = N''
                 AND LTRIM(RTRIM(CAST(ISNULL(tt.NOMBRE, N'') AS NVARCHAR(100)))) = N''
                THEN CAST(NULL AS NVARCHAR(150))
            WHEN LTRIM(RTRIM(CAST(ISNULL(tt.CODIGO_TIPO_TAREA, N'') AS NVARCHAR(20)))) = N''
                THEN LTRIM(RTRIM(CAST(tt.NOMBRE AS NVARCHAR(100))))
            WHEN LTRIM(RTRIM(CAST(ISNULL(tt.NOMBRE, N'') AS NVARCHAR(100)))) = N''
                THEN LTRIM(RTRIM(CAST(tt.CODIGO_TIPO_TAREA AS NVARCHAR(20))))
            ELSE LTRIM(RTRIM(CAST(tt.CODIGO_TIPO_TAREA AS NVARCHAR(20))))
                 + N' — '
                 + LTRIM(RTRIM(CAST(tt.NOMBRE AS NVARCHAR(100))))
        END AS tipo_tarea_label
    FROM dbo.PQ_PRD_CONCEPTOS_TIEMPO AS c
    LEFT JOIN dbo.PQ_PRD_TIPOS_TAREA AS tt
        ON tt.ID_TIPO_TAREA = c.ID_TIPO_TAREA
    WHERE c.ID_CONCEPTO_TIEMPO = @IdConceptoTiempo;
END
GO
